import { Inter } from "next/font/google";
import "./globals.css";
import DarkModeSwitch from "@/components/design/ui/dark-mode-switch";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <DarkModeSwitch>{children}</DarkModeSwitch>
      </body>
    </html>
  );
}
