import { Markazi_Text, Roboto } from "next/font/google";
import { Analytics } from '@vercel/analytics/react';
import { SpeedInsights } from '@vercel/speed-insights/next';
import GoogleAnalytics from '@/components/uneversal-items/google-analytics';
import { ThemeProvider } from 'next-themes'
import { LayoverGlobalProvider } from "@/context/layover/LayoverGlobalContext";
import LayOverSection from "@/components/uneversal-items/layover/layover-section";
import MainFooter from "@/components/uneversal-items/ui/main-footer";




const markazi_text = Markazi_Text(
  {
    weight: ['400', '500', '600', '700'],
    subsets: ['arabic'],
    display: 'swap',
  }
);

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="ltr" className={` scroll-smooth ${markazi_text.className} relative`}>
      <body className="uni-background transition-all duration-200 min-h-screen">
        <GoogleAnalytics />
        {/* <DarkModeSwitch > */}
        <ThemeProvider attribute="class" defaultTheme='system' enableSystem>
          <div className="uni-background">
            <LayoverGlobalProvider>
              <LayOverSection />
              {/* <NavBar /> */}
              {children}
              <MainFooter />
            </LayoverGlobalProvider>
          </div>
        </ThemeProvider>
        {/* </DarkModeSwitch> */}
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
