import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Markazi_Text, Roboto } from "next/font/google";
import "./globals.css";

const markazi_text = Markazi_Text(
  {
    weight: ['400', '500', '600', '700'],
    subsets: ['arabic'],
    display: 'swap',
  }
);

const roboto = Roboto(
  {
    weight: ['100', '300', '400', '500', '700'],
    subsets: ['latin'],
    display: 'swap',
  }
);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`scroll-smooth ${markazi_text.className} antialiased font-sans`}
      >
        {children}
      </body>
    </html>
  );
}
