import { Inter } from "next/font/google";
import "@/assets/styles/globals.css";
import NavBar from "@/components/blog-components/ui/navigation/navbar";
// import DarkModeSwitch from "@/components/blog-components/ui/dark-mode/dark-mode-switch";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="ar" dir="rtl">
        <body className="transition-all duration-200">
          {/* <DarkModeSwitch > */}
          <NavBar />
          {children}
          {/* </DarkModeSwitch> */}
        </body>
      </html>
  );
}
